# Site
repository: nTahiri/resume
favicon: images/favicon.ico

# Personal info
name: Nabil Tahri, B. Eng
title: FullStack & Cloud Developer
email: nabil.tahri@polymtl.ca
website: https://github.com/nTahiri

# Social links
twitter_username: NT_NTahri
github_username:  nTahiri
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: ntahri
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/IMG_0188.jpg
about_content: | # this will include new lines to allow paragraphs
  Bachelor of Engineering
  Full Stack Developer with DevOps Engineering experience
  Team player, with passions in new technology and emerging technology industry practices
  Interest in distributed architectural systems, Mobil development, and cloud computing
  +1 (514) 662-2762

  I am most skilled in: <mark>GoLang</mark>, <mark>Kibernetes - Openshift</mark> and <mark>Jenkins - Tekton - circleci</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - VolleyBall
   - CrossFit

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-modernist